appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: v3k5ww7E6ZZfltYoGZN5IMI8PlFESTGza5aX+jKPfw6bG0C2ltWCrQHpK6YjHqes+Kr0EN2iP2vO6+Yc0eAXOP/CegGXH7Ei4l8sofqL1gWDUbL3FoVNj2/Z6lrD+mV7/tb5f3FyUqFBpffRAR2iicf7x37oe9VoTy3Zqz8RxlKgUrQivhI4jot3A9/HZWd+rtiOC1/DwMINYZiN8JWFdBwnjCT80Jy9cr4drFlffi+DFcxkOpB6O/bvidiKPkgHN39gW76nlY95UZE9ANZSdL+jSo5BuB7pQE2x7WF2MdaV4vAYfnlE+H2aBXinpPQZfzCd+/Ym6lhUH4Pg3HOLRzS4rrBE33Z48sXyEyIiNk5tPzaO1DzFLHTOuDIxITWGBQNqztC859qu5fO/wIqmB16w/8BLIZ1NWvqF7hV6VPsm7K13ezIX9A/vVpSo9FsiTAoznHi5Avb4p6O1pvAIqC99SoJDBEE1ioTApISYYH0hD4XI6D0HkDqlZjthXlTbkaZ0odvC0WYFyjHlckRaQkMRhtCPjJiaoAeC+RMhrpYQJaVLAZu1SXIflc61NZpm2j69R9a/ItLIEjU7L6+ggbsSZm6XqkXM5IrCNPbuvfsJedZdfHZN9g68hxXfqZ58S7rNP2i9tLJBsWmA3nzgoB5JVRnJA3Z+01Bz42qO17o=}
conda_forge_output_validation: true
